# Generated by Django 2.2.5 on 2022-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='Enter your phone number as +63(phone number), e.g +6391-234-5678', max_length=20, null=True),
        ),
    ]
