# Generated by Django 2.2.5 on 2022-10-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20221005_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
