# Generated by Django 2.2.5 on 2022-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_usershippingaddress_brgy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
