# Generated by Django 2.2.5 on 2022-10-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20221006_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='delivery_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='total_order_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='total_order_items',
            field=models.IntegerField(null=True),
        ),
    ]
