# Generated by Django 2.2.5 on 2022-10-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20221009_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
