# Generated by Django 2.2.5 on 2022-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20221009_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='ordered_items',
            field=models.TextField(null=True),
        ),
    ]
