# Generated by Django 2.2.5 on 2022-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_productorder_ordered_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FOR DELIVERY', 'FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=20),
        ),
    ]
