# Generated by Django 2.2.5 on 2022-10-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20221014_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pending_balance',
        ),
    ]
